### ISSUE TITLE
Reverse order meeting minutes archive

### ISSUE THREAD

**Issue by SKBruck** [allhandsactive/board#2]

**Comment by artlogic** [comment]
Could you add a bit of detail here? Is there a problem with the ordering, or is this something else entirely?

**Comment by SKBruck** [comment]
I just pulled the basic archive code from the jekyll website, and I think that that orders the archive from oldest to newest, but the minutes should be ordered newest to oldest for improved user experience. People want to know what happened at the last meeting without having to scroll a bunch.

**Comment by artlogic** [comment]
You should test this, but I think this code will do the trick:

```
{% for post in site.posts reversed %} 
```

**Comment by SKBruck** [comment]
Yeah, that will work - I just wanted to focus on the README and didn't want to forget to do this.

**Comment by artlogic** [comment]
@SKBruck I added the code - see the commit above. Please review and close if it's OK.

**Comment by artlogic** [comment]
I'm going to assume this is ok.
